# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Analyze & Test package

on:
  push:
  pull_request:
jobs:
  analyze:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      
      - name: "Analyze"
        run: flutter pub get && flutter analyze .

      - name: "Format"
        run: flutter format lib/** --set-exit-if-changed

      - name: "Run tests"
        run: flutter test -r expanded
